examples/neo4j/ruby/neo4j_starter/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts do
    resources :comments, except: [:new]
  end

  root 'posts#index'

end

examples/neo4j/ruby/neo4j_starter/app/models/comment.rb
class Comment
    include Neo4j::ActiveNode
    property :author, :type => String
    property :email, :type => String  
    property :content, :type => String
    property :created_at

    has_one(:post).from(:comments)    

    index :author
end

examples/neo4j/ruby/neo4j_starter/app/models/post.rb
class Post 
    include Neo4j::ActiveNode
    property :title, :type => String 
    property :content, :type => String
    property :author, :type => String
    property :created_at

    has_n(:comments).to(Comment)

    index :title

end

examples/neo4j/ruby/neo4j_starter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

examples/neo4j/ruby/neo4j_starter/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :create]

  def index
    @comments = Comment.all
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      @post.comments << @comment
      #No foreign keys, so have to manually push it into the :comments relation array
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @post, notice: 'Comment was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to @post
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params[:comment]
    end

    def set_post
      @post = Post.find(params[:post_id])
    end
end

examples/neo4j/ruby/neo4j_starter/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params[:post]
    end
end

examples/neo4j/ruby/neo4j_starter/app/helpers/application_helper.rb
module ApplicationHelper
end

examples/neo4j/ruby/neo4j_starter/app/helpers/comments_helper.rb
module CommentsHelper
end

examples/neo4j/ruby/neo4j_starter/app/helpers/posts_helper.rb
module PostsHelper
end

examples/neo4j/ruby/neo4j_starter/app/views/comments/_new.html.erb
<div class="comment-field">
<h3>New comment</h3>

<%= form_for [@post, Comment.new] do |f| %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 6, style:"width: 490px" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

examples/neo4j/ruby/neo4j_starter/app/views/comments/_show.html.erb
<div class="comment comment-header">
<span class="comment-author">
  <strong>Author:</strong>
  <%= c.author %>
</span>
<span class="comment-email">
  <strong>Email:</strong>
  <%= c.email %>
</span>
<span class="comment-time">
	<%= c.created_at.strftime("%x: %I:%M %p") %>
</span>
</div>


<div class="comment comment-body">
<p>
  <%= c.content %>
</p>
</div>
<div class="comment comment-footer">
<%= link_to 'Edit', edit_post_comment_path(@post, c) %>
<%= link_to 'Destroy', [@post, c], method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

examples/neo4j/ruby/neo4j_starter/app/views/comments/edit.html.erb
<div class="comment-field">
<h3>Edit comment</h3>

<%= form_for [@post, @comment] do |f| %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 6, style:"width: 490px" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

examples/neo4j/ruby/neo4j_starter/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.email %></td>
        <td><%= comment.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

examples/neo4j/ruby/neo4j_starter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<%= yield %>
</div>

</body>
</html>

examples/neo4j/ruby/neo4j_starter/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

examples/neo4j/ruby/neo4j_starter/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

examples/neo4j/ruby/neo4j_starter/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.author %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

examples/neo4j/ruby/neo4j_starter/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

examples/neo4j/ruby/neo4j_starter/app/views/posts/show.html.erb
<h3>Posted: <%= @post.created_at.strftime('%x') %></h3>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<h3>Comments:</h3>
<% @comments.each do |comment| %>
	<%= render 'comments/show', c:comment %>
<% end %>
<%= render 'comments/new' %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>