examples/neo4j/ruby/movies-with-neo4j-master/config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: [:show, :index], param: :title
  resources :people, only: [:show, :index], param: :name

  root 'movies#index'

  get 'search' => 'search#index'

end

examples/neo4j/ruby/movies-with-neo4j-master/app/models/acted_in.rb
class ActedIn
  include Neo4j::ActiveRel

  from_class :Person
  to_class :Movie

  property :roles

  def rel_type
    type
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/models/movie.rb
class Movie
  include Neo4j::ActiveNode
  property :title
  property :released
  property :tagline

  has_many :in, :people, type: false
  has_many :in, :actors, type: :ACTED_IN, model_class: :Person
  has_many :in, :directors, type: :DIRECTED, model_class: :Person
  has_many :in, :producers, type: :PRODUCED, model_class: :Person
  has_many :in, :writers, type: :WROTE, model_class: :Person

  scope :search, -> (query) { where(title: Regexp.new("(?i).*#{query}.*")) }

  def self.people_in_movies
    all(:m).people(:p).pluck('m.uuid', 'count(p)').to_h
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/models/person.rb
class Person
  include Neo4j::ActiveNode
  property :name
  property :born

  has_many :out, :movies, type: false

  has_many :out, :movies_acted_in, type: :ACTED_IN, model_class: :Movie
  has_many :out, :movies_directed, type: :DIRECTED, model_class: :Movie
  has_many :out, :movies_produced, type: :PRODUCED, model_class: :Movie
  has_many :out, :movies_wrote, type: :WROTE, model_class: :Movie

  def self.movies_by_people
    all(:p).movies(:m).pluck('p.uuid', 'count(m)').to_h
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :fetch_movies, only: [:index]

  def index
    @people_in_movies = Movie.people_in_movies
  end

  def show
    @movie = Movie.find_by(title: params[:title])
  end

  def fetch_movies
    @movies = Movie.all
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
    @movies_by_people = Person.movies_by_people
  end

  def show
    @person = Person.find_by(name: params[:name])
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    q = params[:q] || ''
    @movies = q.empty? ? [] : Movie.search(q)
    @people_in_movies = Movie.people_in_movies
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/helpers/application_helper.rb
module ApplicationHelper
  def relationship_to_human
    { ACTED_IN: 'acted' }
  end

  def humanize_relation(relationship)
    relationship_to_human[relationship] || ''
  end
end

examples/neo4j/ruby/movies-with-neo4j-master/app/helpers/movies_helper.rb
module MoviesHelper
end

examples/neo4j/ruby/movies-with-neo4j-master/app/helpers/people_helper.rb
module PeopleHelper
end

examples/neo4j/ruby/movies-with-neo4j-master/app/helpers/search_helper.rb
module SearchHelper
end

examples/neo4j/ruby/movies-with-neo4j-master/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MoviesWithNeo4j"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_url } Movies app
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Movies", movies_path
            %li= link_to "People", people_path
          %form(class="navbar-form navbar-right" role="search" action="/search")
            .form-group
              %input(type="text" class="form-control" placeholder="Search" name="q")
            %button.btn.btn-default( type="submit") Submit

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      %footer

examples/neo4j/ruby/movies-with-neo4j-master/app/views/movies/_movies.haml
.row
  .col-lg-9.col-md-12
    .list-group
      - movies.each do |movie|
        = link_to movie_path(movie.title), class: 'list-group-item' do
          = movie.title
          -# slower method to count the people involved in each movie
          -#= "(#{movie.people.count})"
          %span.badge
            = people_in_movies[movie.uuid]

examples/neo4j/ruby/movies-with-neo4j-master/app/views/movies/index.haml
%h1 Movies

= render partial: 'movies', locals: {movies: @movies, people_in_movies: @people_in_movies}
      
  

examples/neo4j/ruby/movies-with-neo4j-master/app/views/movies/show.haml
%h1
  = @movie.title

%p
  Released:
  = @movie.released

%p
  Tagline:
  = @movie.tagline

%ul
  - @movie.people.each_with_rel do |person, rel|
    %li
      = link_to person.name, person_path(person.name)
      = humanize_relation(rel.rel_type)
      - roles = Array(rel.props[:roles]).to_sentence(:last_word_connector => ' and ')
      - if roles.present?
        as
        = roles

examples/neo4j/ruby/movies-with-neo4j-master/app/views/people/_people.haml
.row
  .col-lg-9.col-md-12
    .list-group
      - people.each do |person|
        = link_to person_path(person.name), class: 'list-group-item' do
          = person.name
          %span.badge
            = movies_by_people[person.uuid].to_i

examples/neo4j/ruby/movies-with-neo4j-master/app/views/people/index.haml
%h1 People

= render partial: 'people', locals: {people: @people, movies_by_people: @movies_by_people}

examples/neo4j/ruby/movies-with-neo4j-master/app/views/people/show.haml
%h1
  = @person.name

%ul
  - @person.movies.each_with_rel do |movie, rel|
    %li
      = link_to movie.title, movie_path(movie.title)
      = humanize_relation(rel.rel_type)

      - roles = Array(rel.props[:roles]).to_sentence(last_word_connector: ' and ')
      - if roles.present?
        as
        = roles

examples/neo4j/ruby/movies-with-neo4j-master/app/views/search/index.haml
%h1 Search

%h2 Movies
= render partial: 'movies/movies', locals: {movies: @movies, people_in_movies: @people_in_movies}